/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package milestone2;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bryan
 */
public class DeanPage extends javax.swing.JFrame {

    /**
     * Creates new form Dean
     */
    public DeanPage() {
        initComponents();
    }
    public Person uname;

    public DeanPage(Person p) {
        initComponents();
        uname = p;
        jAlert.setText(p.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jAlert = new javax.swing.JLabel();
        btnPersonalLeave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPendingTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnViewPending = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplayArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jRejectedtbl = new javax.swing.JTable();
        btnViewApproved = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jApprovedtbl = new javax.swing.JTable();
        btnViewRejected = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jAlert.setText("Dean");

        btnPersonalLeave.setText("Personal Leave");
        btnPersonalLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalLeaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPersonalLeave)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAlert)
                    .addComponent(btnPersonalLeave))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jPendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department", "Leave ID", "Type", "Days", "Start Day", "End Day", "Status"
            }
        ));
        jPendingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPendingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jPendingTable);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pending Leave Requests");

        btnViewPending.setBackground(new java.awt.Color(51, 153, 0));
        btnViewPending.setText("View Pending Requests");
        btnViewPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPendingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jLabel2)
                .addContainerGap(551, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPending)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDisplayArea.setColumns(20);
        txtDisplayArea.setRows(5);
        jScrollPane2.setViewportView(txtDisplayArea);

        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REJECT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jRejectedtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department", "Leave ID", "Type", "Days", "Start Day", "End Day", "Status"
            }
        ));
        jRejectedtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRejectedtblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jRejectedtbl);

        btnViewApproved.setBackground(new java.awt.Color(51, 153, 0));
        btnViewApproved.setText("View Approved Requests");
        btnViewApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApprovedActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Approved Requests");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                    .addComponent(btnViewApproved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewApproved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        jApprovedtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department", "Leave ID", "Type", "Days", "Start Date", "End Date", "Status"
            }
        ));
        jApprovedtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jApprovedtblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jApprovedtbl);

        btnViewRejected.setBackground(new java.awt.Color(51, 153, 0));
        btnViewRejected.setText("View Rejected Requests");
        btnViewRejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRejectedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rejected Requests");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                    .addComponent(btnViewRejected, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewRejected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int index = jPendingTable.getSelectedRow();
        TableModel model = jPendingTable.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        String value2 = model.getValueAt(index, 1).toString();
        String value3 = model.getValueAt(index, 2).toString();
        String value4 = model.getValueAt(index, 3).toString();
        String value5 = model.getValueAt(index, 4).toString();
        String value6 = model.getValueAt(index, 5).toString();
        String value7 = model.getValueAt(index, 6).toString();
        String value8 = model.getValueAt(index, 7).toString();
        String value9 = model.getValueAt(index, 8).toString();
        String value10 = model.getValueAt(index, 9).toString();
        String value11 = model.getValueAt(index, 10).toString();
        String value12 = model.getValueAt(index, 11).toString();

        String choice = value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12;

        String oldStatus = "Approved";

        Datahandler dh = new Datahandler();
        dh.connectToDB();

        try {
            if (dh.UpdateEmployeeLeaveRequest(value1, value2, Integer.parseInt(value3), value4, value5, Integer.parseInt(value6), Integer.parseInt(value7), value8, Integer.parseInt(value9), value10, value11, oldStatus, value12, value1)) {
                JOptionPane.showMessageDialog(this, "Employee Leave Request Was Approved!");
            } else {
                JOptionPane.showMessageDialog(this, "Employee Leave Request Not Approved!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Employee Leave Request Not Approved!" + e.getMessage());
        }

        String dateError = "";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void populatePendingRequests() {
        Datahandler dh = new Datahandler();
        List<LeaveType> pending = null;
        try {
            pending = dh.populatePendingtbl("Pending");
        } catch (Exception ex) {
            Logger.getLogger(DeanPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jPendingTable.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : pending) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jPendingTable.setModel(tm);
    }

    public void populateApprovedRequests() {
        Datahandler dh = new Datahandler();
        List<LeaveType> approved = null;
        try {
            approved = dh.populatePendingtbl("Approved");
        } catch (Exception ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jRejectedtbl.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : approved) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jRejectedtbl.setModel(tm);
    }

    public void populateRejectedRequests() {
        Datahandler dh = new Datahandler();
        List<LeaveType> rejected = null;
        try {
            rejected = dh.populatePendingtbl("Rejected");
        } catch (Exception ex) {
            Logger.getLogger(DeanPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jApprovedtbl.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : rejected) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jApprovedtbl.setModel(tm);
    }


    private void btnViewPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPendingActionPerformed
        populatePendingRequests();
    }//GEN-LAST:event_btnViewPendingActionPerformed


    private void btnViewRejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRejectedActionPerformed
        populateRejectedRequests();
    }//GEN-LAST:event_btnViewRejectedActionPerformed

    private void btnViewApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApprovedActionPerformed

        populateApprovedRequests();
    }//GEN-LAST:event_btnViewApprovedActionPerformed

    public void ClearDisplayArea() {
        txtDisplayArea.setText("");
    }


    private void jPendingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPendingTableMouseClicked

        ClearDisplayArea();

        int index = jPendingTable.getSelectedRow();
        TableModel model = jPendingTable.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        String value2 = model.getValueAt(index, 1).toString();
        String value3 = model.getValueAt(index, 2).toString();
        String value4 = model.getValueAt(index, 3).toString();
        String value5 = model.getValueAt(index, 4).toString();
        String value6 = model.getValueAt(index, 5).toString();
        String value7 = model.getValueAt(index, 6).toString();
        String value8 = model.getValueAt(index, 7).toString();
        String value9 = model.getValueAt(index, 8).toString();
        String value10 = model.getValueAt(index, 9).toString();
        String value11 = model.getValueAt(index, 10).toString();
        String value12 = model.getValueAt(index, 11).toString();

        String choice = value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12;

        String dateError = "";

        txtDisplayArea.append(" " + choice.toString() + "\n");
    }//GEN-LAST:event_jPendingTableMouseClicked

    private void jRejectedtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRejectedtblMouseClicked

        ClearDisplayArea();

        int index = jRejectedtbl.getSelectedRow();
        TableModel model = jRejectedtbl.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        String value2 = model.getValueAt(index, 1).toString();
        String value3 = model.getValueAt(index, 2).toString();
        String value4 = model.getValueAt(index, 3).toString();
        String value5 = model.getValueAt(index, 4).toString();
        String value6 = model.getValueAt(index, 5).toString();
        String value7 = model.getValueAt(index, 6).toString();
        String value8 = model.getValueAt(index, 7).toString();
        String value9 = model.getValueAt(index, 8).toString();
        String value10 = model.getValueAt(index, 9).toString();
        String value11 = model.getValueAt(index, 10).toString();
        String value12 = model.getValueAt(index, 11).toString();

        String choice = value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12;

        String dateError = "";

        txtDisplayArea.append("CHOICE : " + " " + choice + "\n");
    }//GEN-LAST:event_jRejectedtblMouseClicked

    private void jApprovedtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jApprovedtblMouseClicked
        ClearDisplayArea();

        int index = jApprovedtbl.getSelectedRow();
        TableModel model = jApprovedtbl.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        String value2 = model.getValueAt(index, 1).toString();
        String value3 = model.getValueAt(index, 2).toString();
        String value4 = model.getValueAt(index, 3).toString();
        String value5 = model.getValueAt(index, 4).toString();
        String value6 = model.getValueAt(index, 5).toString();
        String value7 = model.getValueAt(index, 6).toString();
        String value8 = model.getValueAt(index, 7).toString();
        String value9 = model.getValueAt(index, 8).toString();
        String value10 = model.getValueAt(index, 9).toString();
        String value11 = model.getValueAt(index, 10).toString();
        String value12 = model.getValueAt(index, 11).toString();

        String choice = value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12;

        String dateError = "";

        txtDisplayArea.append("CHOICE : " + " " + choice + "\n");
    }//GEN-LAST:event_jApprovedtblMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ClearDisplayArea();

        int index = jRejectedtbl.getSelectedRow();
        TableModel model = jRejectedtbl.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        String value2 = model.getValueAt(index, 1).toString();
        String value3 = model.getValueAt(index, 2).toString();
        String value4 = model.getValueAt(index, 3).toString();
        String value5 = model.getValueAt(index, 4).toString();
        String value6 = model.getValueAt(index, 5).toString();
        String value7 = model.getValueAt(index, 6).toString();
        String value8 = model.getValueAt(index, 7).toString();
        String value9 = model.getValueAt(index, 8).toString();
        String value10 = model.getValueAt(index, 9).toString();
        String value11 = model.getValueAt(index, 10).toString();
        String value12 = model.getValueAt(index, 11).toString();

        String choice = value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12;

        String oldStatus = "Rejected";

        Datahandler dh = new Datahandler();
        dh.connectToDB();

        try {
            if (dh.UpdateEmployeeLeaveRequest(value1, value2, Integer.parseInt(value3), value4, value5, Integer.parseInt(value6), Integer.parseInt(value7), value8, Integer.parseInt(value9), value10, value11, oldStatus, value12, value1)) {
                JOptionPane.showMessageDialog(this, "Employee Leave Request Was Rejected!");
            } else {
                JOptionPane.showMessageDialog(this, "Employee Leave Request Rejection Failed!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Employee Leave Request Not Approved!" + e.getMessage());
        }

        String dateError = "";
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPersonalLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalLeaveActionPerformed
        Datahandler dh = new Datahandler();
        Person p = new Person();
        try {
            p = dh.GetUserInfo(jAlert.getText());
            EmployeeLeaveRequestPage elp = new EmployeeLeaveRequestPage(p);
            elp.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPersonalLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeanPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonalLeave;
    private javax.swing.JButton btnViewApproved;
    private javax.swing.JButton btnViewPending;
    private javax.swing.JButton btnViewRejected;
    private javax.swing.JLabel jAlert;
    private javax.swing.JTable jApprovedtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTable jPendingTable;
    private javax.swing.JTable jRejectedtbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtDisplayArea;
    // End of variables declaration//GEN-END:variables
}
