package milestone2;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import milestone2.Datahandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bryan
 */
public class ViewLeaveHistory extends javax.swing.JFrame {

    /**
     * Creates new form ViewLeaveHistory
     */
    public ViewLeaveHistory() {
        initComponents();
    }
    public Person userman;

    public ViewLeaveHistory(Person p) {
        initComponents();
        lblTextChange.setText(p.getName());
        userman = p;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTextChange = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPendingtbl = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewPending = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jApprovedTable = new javax.swing.JTable();
        btnViewApproved = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jRejectedTable = new javax.swing.JTable();
        btnViewRejected = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Leave History For ");

        lblTextChange.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblTextChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTextChange))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));

        jPendingtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department ID", "Leave ID", "Type", "Days", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jPendingtbl);

        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewPending.setBackground(new java.awt.Color(51, 153, 0));
        btnViewPending.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnViewPending.setText("View All Pending Requests");
        btnViewPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPendingActionPerformed(evt);
            }
        });

        jApprovedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department ID", "Leave ID", "Type", "Days", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(jApprovedTable);

        btnViewApproved.setBackground(new java.awt.Color(51, 153, 0));
        btnViewApproved.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnViewApproved.setText("ViewAll Approved Requests");
        btnViewApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApprovedActionPerformed(evt);
            }
        });

        jRejectedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Email", "Phone", "Department ID", "Leave ID", "Type", "Days", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane3.setViewportView(jRejectedTable);

        btnViewRejected.setBackground(new java.awt.Color(51, 153, 0));
        btnViewRejected.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnViewRejected.setText("View All Rejected Requests");
        btnViewRejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRejectedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pending Leave Requests");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Approved History");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rejected History");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                            .addComponent(btnViewRejected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewApproved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewPending, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPending)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewApproved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewRejected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Datahandler dh = new Datahandler();
        Person p = new Person();
        try {
            p = dh.GetUserInfo(userman.getName());
            EmployeeLeaveRequestPage elp = new EmployeeLeaveRequestPage(p);
            elp.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ViewLeaveHistory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ViewLeaveHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    public void populatePendingRequests(String word) {
        Datahandler dh = new Datahandler();
        List<LeaveType> pending = null;
        try {
            pending = dh.populatePendingtblSingleUser(word, userman.getName());
        } catch (Exception ex) {
            Logger.getLogger(DeanPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jPendingtbl.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : pending) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jPendingtbl.setModel(tm);
    }

    public void populateApprovedRequests(String word) {
        Datahandler dh = new Datahandler();
        List<LeaveType> approved = null;
        try {
            approved = dh.populatePendingtblSingleUser(word, userman.getName());
        } catch (Exception ex) {
            Logger.getLogger(DeanPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jApprovedTable.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : approved) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jApprovedTable.setModel(tm);
    }

    public void populateRejectedRequests(String word) {
        Datahandler dh = new Datahandler();
        List<LeaveType> rejected = null;
        try {
            rejected = dh.populatePendingtblSingleUser(word, userman.getName());
        } catch (Exception ex) {
            Logger.getLogger(DeanPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tm = (DefaultTableModel) jRejectedTable.getModel();
        int rowCount = tm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (LeaveType leaveType : rejected) {

            Object[] obj = new Object[12];
            obj[0] = leaveType.getName();
            obj[1] = leaveType.getSurname();
            obj[2] = leaveType.getAge();
            obj[3] = leaveType.getEmail();
            obj[4] = leaveType.getPhone();
            obj[5] = leaveType.getDepartmentID();
            obj[6] = leaveType.getLID();
            obj[7] = leaveType.getLName();
            obj[8] = leaveType.getTotalDays();
            obj[9] = leaveType.getStartDate();
            obj[10] = leaveType.getEndDate();
            obj[11] = leaveType.getStatus();

            tm.addRow(obj);
        }
        jRejectedTable.setModel(tm);
    }
    private void btnViewPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPendingActionPerformed
        String word = "Pending";
        populatePendingRequests(word);
    }//GEN-LAST:event_btnViewPendingActionPerformed

    private void btnViewApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApprovedActionPerformed
        String word = "Approved";
        populateApprovedRequests(word);
    }//GEN-LAST:event_btnViewApprovedActionPerformed

    private void btnViewRejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRejectedActionPerformed
        String word = "Rejected";
        populateRejectedRequests(word);
    }//GEN-LAST:event_btnViewRejectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLeaveHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLeaveHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLeaveHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLeaveHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLeaveHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewApproved;
    private javax.swing.JButton btnViewPending;
    private javax.swing.JButton btnViewRejected;
    private javax.swing.JTable jApprovedTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jPendingtbl;
    private javax.swing.JTable jRejectedTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTextChange;
    // End of variables declaration//GEN-END:variables
}
